version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    network_mode: host
  my-project:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_ADDR=127.0.0.1:6379
    network_mode: host
